version: "3"
services:
  elasticsearch:
    #image: elasticsearch:7.13.4
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'

  logstash:
    image: logstash
    container_name: logstash
    build:
        context: logstash/.
        dockerfile: Dockerfile
    ports:
        - "9600:9600"
        - "8089:8089"
        - "5044:5044"

  filebeat:
    image: filebeat
    container_name: filebeat
    build:
        context: filebeat/.
        dockerfile: Dockerfile
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/log/app/:/home/
  
  micrologs:
    image: micrologs:latest
    container_name: micrologs
    env_file: logs/environment.env
    build:
        context: logs/.
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
        - /etc/localtime:/etc/localtime:ro
  
  fastapi:
    image: fastapilogs
    container_name: fastapilogs
    build:
        context: ./fastapi
        dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/log/app/:/app/logs/
        
volumes:
  data01:
    driver: local